version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: "travelus_redis_server"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "travelus_booking"
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8088 --timeout-keep-alive 120 --workers 3
    volumes:
      - .:/app
      - ./logs:/var/log/app  # Map the local logs directory to /var/log/app in the container
    depends_on:
      - redis
    env_file:
      - .env  # Load environment variables from a .env file

volumes:
  redis_data: